# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PENYADAP.GITHUB.IO
email: your-email@domain.com
description: >
  Blog khusus mengulas tentang info digital
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://penyadap.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage
permalink: /:title/

name: 'penyadap.github.io'
bio: >
  Ulasan tentang ponsel iphone, android dan berbagai tips lain seperti rooting, penyadap, lacak, juga berbagai info menarik tentang dunia teknologi.
author_image: "/assets/images/author.jpg"
twitter_username: jekyllrb
github_username:  jekyll

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
